### ISSUE TITLE
project recommend

### ISSUE THREAD

**Issue by Lionad-Morotar** [ghoullier/awesome-template-literal-types#32]
Hi, I have written a project using Template Literal Types called Anysort, can I request that it be included in readme.md?
你好，我使用 Template Literal Types 写了一个项目，叫 Anysort，能否请求把它收录到 readme.md 中？

Anysort：https://github.com/Lionad-Morotar/Anysort

![image](https://user-images.githubusercontent.com/26913795/177392337-a6a0117f-f32e-4ed1-9dd6-dabbb802cdab.png)

**Comment by ghoullier** [comment]
Hi @Lionad-Morotar
Thanks for your contribution. Your example have been merged in `main` branch.
